
- name: Install required software for http web server
  apt: 
    name:
      - git
      - unzip
      - ufw
      - apache2
      - apache2-utils
      - php{{ php_version }}
      - php{{ php_version }}-mysql
      - libapache2-mod-php{{ php_version }}
      - python-mysqldb
      - mariadb-client
      - php-cli
      - php{{ php_version }}-cli 
      - php{{ php_version }}-zip
      - php{{ php_version }}-curl
      - php{{ php_version }}-xml
      - php{{ php_version }}-intl
      - php{{ php_version }}-gd
      - php{{ php_version }}-mbstring
      - wget
    state : present
  become: yes

# - name execute composer deb Install
#   shell: "php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');""
#   become: yes