- name: "Create Dockerfile - prestashop"
  template:
    src: "Jenkinsfile.j2"
    dest: "{{work_dir}}/src/Jenkinsfile"

- name: Change the working directory to {{work_dir}}/src/ before init repo.
  shell: git add  && git add Jenkinsfile && git commit -m "Jenkinsfile add commit"
  args:
    chdir: "{{work_dir}}/src/"