- name: "Create Dockerfile - prestashop"
  template:
    src: "Jenkinsfile.j2"
    dest: "{{prestashop_src_dir}}/Jenkinsfile"

- name: Change the working directory to {{prestashop_src_dir}}/ before init repo.
  shell: git add  && git add Jenkinsfile && git commit -m "Jenkinsfile add commit"
  args:
    chdir: "{{prestashop_src_dir}}/"