- name: Download WordPress  
  get_url: 
    url: https://github.com/PrestaShop/PrestaShop/releases/download/{{ps_version}}/prestashop_{{ps_version}}.zip
    #https://www.prestashop.com/fr/file/prestashop_1-7-6-7-zip/download?token=NP1tniK9
    #https://hub.docker.com/r/prestashop/prestashop-git/dockerfile
    #https://github.com/bitnami/bitnami-docker-prestashop
    dest: "{{ tmp_dir }}/"
    force: no
  become: yes

- name: Extract Prestashop
  become: yes
  become_method : sudo
  unarchive: 
    src: "{{ tmp_dir }}/prestashop_{{prestashop_git_branch}}.zip"
    dest: "{{prestashop_directory}}"
    #extra_opts: [--strip-components=1]
    #remote_src: yes
    remote_src: yes
    extra_opts: "-j"

# - name: subtitute for rendering wp-config.php 
#   template:
#     src: "wp-config.php.j2"
#     dest: "{{ prestashop_directory }}/wp-config.php"
#   tags: [ wordpress ]

# - name: Remove sample file =  {{ wordpress_directory }}/wp-config-sample.php 
#   file:
#     state: absent
#     path: "{{ wordpress_directory }}/wp-config-sample.php"
#   become: yes

## TODO : verifi wp-config-sample.php

- name: Attempt to change ownership on {{ wordpress_directory }}
  file:
    path: "{{ prestashop_directory }}"
    state: directory
    recurse: yes
    owner: "{{app_user}}"
    group: "{{app_user}}"
    mode: '0755'
  become: yes

- name: Set permissions for files into {{ prestashop_directory }} directory
  shell: "/usr/bin/find {{ prestashop_directory }} -type f -exec chmod 640 {} \\;"
  tags: [ wordpress ] 