- name:  check work directory if exist [{{work_dir}}]
  stat:
    path: "{{work_dir}}/"
  register: wfolder

- name: remove files and directories
  file:
    state: "{{ item }}"
    path: "{{work_dir}}/"
    owner: 1000  # set your owner, group, and mode accordingly
    group: 1000
    mode: '0777'
  with_items:
    - absent
    - directory
  when: wfolder.stat.exists


- name: "Ansible Create {{work_dir}}/src directory if not exists"
  file:
    path: "{{work_dir}}/src"
    state: directory
    mode: 0755
    owner: "{{sys_user}}"
    group: docker

#TODO : GIT my repos
- name: "Recuperation du souce github de prestashop : branche : {{prestashop_git_branch}}"
  git:
    repo: "{{prestashop_git_repo}}"
    dest: "{{work_dir}}/src/"
    version: "{{prestashop_git_branch}}"
    depth: 50
    force: "yes"
    accept_hostkey: "yes"

- name: suppression du dossier .git
  file :
    path: "{{work_dir}}/src/.git"
    state: absent

- name: Change the working directory to {{work_dir}}/src/ before init repo.
  shell: git init && git add . && git commit -m "initial commit"
  args:
    chdir: "{{work_dir}}/src/"


- name: Ansible Create {{work_dir}}/resources directory if not exists
  file:
    path: "{{work_dir}}/resources"
    state: directory
    mode: 0755
    owner: "{{sys_user}}"
    group: docker

- name: "copy docker resource for prestashop & mysql"
  copy:
    src: "{{role_path}}/files/"
    dest: "{{work_dir}}/resources/"
    owner: "{{sys_user}}"
    group: docker
    mode: u=rw,g=r,o=r

- name: chmod *.sh fille 0755   
  command: find {{work_dir}}/resources -type f -name "*.sh" ! -perm 0755 -exec chmod 0755 {} \;
  
- name: Create docker-compose.yml file
  template:
    src: "prestashop-git-docker-compose.yml.j2"
    dest: "{{work_dir}}/docker-compose.yml"

- name: "change docker-compose.yml owner"
  file:
    path: "{{work_dir}}/docker-compose.yml"
    state: file
    mode: 0755
    owner: "{{sys_user}}"
    group: docker
  when: wfolder.stat.exists == false


