jenkins_version : 2.244

domain: ps.melbeied.net
httpd_conf : prestashop.conf
http_port : 80
php_version: 7.3
prestashop_git_branch : 1.7.7.x
prestashop_git_repo: https://github.com/PrestaShop/PrestaShop.git
docker_compose_version : 2
tmp_dir : /tmp
work_dir: ../project