---
- name : Installation Jenkins and PrestaShop for Selenium acceptance tests
  hosts: 127.0.0.1
  connection : local 
  remote_user: vagrant
  gather_facts: yes
  become: yes 
  vars_files:
    - vars/main.yml
    - vars.yml
  
  # pre_tasks:
  #   - name : "PRE TACKS"
  #     shell: echo 'hello in pre'
  roles:
    # - jenkins
    #- prestashop
    - selenium
    #- geerlingguy.composer

  tasks:
    - name : "execute : composer install --no-plugins"
      shell: composer install -d {{prestashop_src_dir}} --no-plugins
      register: out

    - name : show (composer install --no-plugins) output
      debug: 
        var: out.stdout_lines

  # post_tasks:
  #   - name : "POST TACKS"
  #     shell: echo 'goodbye in post'